### ISSUE TITLE
model lock conflicts

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#19]
(moved from [remindmodel issue #841](https://github.com/remindmodel/remind/issues/841))The problem: Both in REMIND and MAgPIE, sometimes, the lock via [gms/model_lock](https://github.com/pik-piam/gms/blob/master/R/model_lock.R) does not work properly and two runs operate simultaneously on gms files or input data, causing failed runs and [wrong data](https://github.com/magpiemodel/magpie/issues/395).

Experience by @dklein-pik, @giannou and @orichters shows it happens mostly when subsequent runs were started, but it was difficult to find a working example that consistently reproduces the behavior. Maybe a parallel cluster hiccup is needed.

- [x] We already [improved the error message in the gms package](https://github.com/pik-piam/gms/pull/17) if something goes wrong with the locking mechanism.
- [ ] For coupled runs, in [this PR](https://github.com/remindmodel/remind/pull/835), I suggest to @dklein to add a sleep of 10 seconds between starting subsequent runs (where we had this problem) to see whether this helps, but we may wish to use it consistently also in the initial start phase and for standalone runs.
- [ ] An alternative could be not to use self-chosen numbers in the model_lock, but rather use some combination of run title with an id or so such that at least all the runs fail instead of thinking everything was fine, but this does not solve the problem, only makes fails more transparent.
- [ ] @mikapfl suggested to eliminate (almost all) locking, which is some work, but maybe worth it given how hard locking is in general and in particular in distributed file systems
- [ ] @mikapfl suggested to use NFS-safe locking which uses hardlinks to lock files because making a hardlink is a guaranteed atomic operation by POSIX, but this requires collision-resistant IDs, like e.g. UUIDs or whatever. Scenario names are not collision-resistant.

**Comment by orichters** [comment]
Keep in mind that the lock file is not only used to lock the model, but contains the queue.

**Comment by mikapfl** [comment]
True, the approach would then be to have a separate queue file, and a lock file for the queue file (because you should not open the lock file for writing because posix is stupid). Then, writing or reading the queue file can be protected with the lock file and thereby, operations on the queue file can be serialized strictly.

**Comment by mikapfl** [comment]
filelock is a great idea, I also tested it on the cluster, works like a charm.

I have two proposals:
1. use filelock, abandon human-readable queues (filelock decides internally who will get the lock next when the current holder releases the lock)
2. use filelock to protect the queues, do queues as they are done currently.

I think I prefer proposal 1 because it has the lowest complexity, but it also gives up the `auto_unlock` functionality etc.
On the other hand, proposal 2 is not more work now (I have done the work to understand the current queuing already), and retains all the current features. However, we are paying this the next time someone has to touch the locking because it will then be a lot more complex than if we go with proposal 1 now (literally 3 lines of code).

**Comment by orichters** [comment]
Sounds great.
1 .What will happen with a file lock if you cancel the slurm job while it has locked the model? ["If a process terminates (with a normal exit, a crash or on a signal), the lock(s) it is holding are automatically released."](https://github.com/r-lib/filelock/blob/main/man/lock.Rd) That seems reasonable. Currently, quite often, you have to edit the file by hand and delete the corresponding rows. I suspect this is also the reason why the auto_unlock was implemented, if somebody just forgot about that. But certainly @tscheypidi can tell you more about the motives.
2. Do you have any idea how the internal decision about "who gets the next lock" is done? FIFO? Or random?

**Comment by mikapfl** [comment]
> What will happen with a file lock if you cancel the slurm job while it has locked the model?

That will automatically release the lock. I just tested with normally terminating R sessions, with R sessions killed with SIGKILL and with R sessions crashing with SEGFAULT. If the process on the compute node is terminated, its lock is released, and a process on another node gets the lock.

> Do you have any idea how the internal decision about "who gets the next lock" is done? FIFO? Or random?

AFAIU, on unix, it is FIFO. But it is not specified by POSIX, so theoretically it could also be filo or random, or the favourite process of the kernel or whatever.

Is ordering important for us?

**Comment by orichters** [comment]
Thanks to @mikapfl and PR #23, this problem is fixed!
